--- 

# - name: create the json from the template
#   template:
#     src: rg_policy.j2
#     dest: /tmp/rg_policy.json

# - name: Create Azure Policy 
#   azure.azcollection.azure_rm_resource:
#     provider: "ResourceGroups"
#     resource_type: resourcegroup
#     resource_name: "{{ rg_policy }}"
#     api_version: "2020-01-01"
#     body: "{{ lookup ('file', 'rg-policy.json') }}"
#   register: output
#   failed_when: output.rc == 0 

- name: Shell out for policy creation
  shell: |
    az policy definition create \
    --name "{{ policy.def.name }}" \
    --display-name "{{ policy.def.name }}" \
    --subscription "{{ subscription }}" \
    --description "{{ policy.def.description }}" \
    --mode all \
    --metadata 'category={{ policy.def.category }}' \
    --rules "{{lookup('file', 'rg-policy.json') | from_json }}"

- name: sleep for 30s and continue 
  wait_for:
    timeout: 30
  delegate_to: localhost

- name: Shell out for policy assignment
  shell: |
    az policy assignment create \
    --scope "{{ policy.assign.scope }}" \
    --policy "{{ policy.def.name }}" 

# - name: get the request token
#   uri:
#     method: PUT
#     url: https://login.microsoftonline.com/64dc69e4-d083-49fc-9569-ebece1dd1408/oauth2/v2.0/authorize?
#     body: |
#       grant_type=client_credentials
#       &redirect_uri=https%3A%2F%2Fredhat.com%2Fansible-app
#       &client_id=44c04d85-b57a-46fb-ba2c-11044eb5ddb3
#       &client_secret="{{ azure_secret }}"
#       &scope=https%3A%2F%2Fredhat.com%2Fansible-app%2Fuser_impersonation
#       &response_type=code
#       &response_mode=query
#   register: token_out

# - name:
#   debug:
#     msg: "{{ token_out }}"

# - name: trying with URI
#   uri:
#     url: "{{ policy_creation_url }}"
#     method: PUT
#     headers:
#       Authorization='Bearer {{ auth_file??? }}'
#     body_format: json
#     body: "{{ lookup ('file', 'rg-policy.json') }}"
