--- 

- name: create the json from the template
  template:
    src: rg_policy.j2
    dest: /tmp/rg_policy.json

- name: Update scaleset info using azure_rm_resource
  azure.azcollection.azure_rm_resource:
    resource_group: "{{ resource_group }}"
    provider: compute
    resource_type: resourcegroup
    resource_name: "{{ rg_policy }}"
    api_version: "2017-12-01"
    body: "{{ rg_policy }}"
  register: output

- debug:
    msg: "{{ output.stderr }}"

- name: Create Resource Group Policy
  azure.azcollection.azure_rm_devtestlabpolicy:
    resource_group: "{{ resource_group }}"
    lab_name: myLab
    policy_set_name: myPolicySet
    name: myPolicy
    fact_name: user_owned_lab_vm_count
    threshold: 5
