---

- name: Create a resource group for each user
  azure_rm_resourcegroup:
    name: "user-{{ item }}"
    location: eastus
    subscription_id: "{{ sub.id }}"
    tags:
        testing: workshop
  with_sequence: start=1 end=10
  tags: [ create, all ]









# https://docs.microsoft.com/en-us/azure/role-based-access-control/role-assignments-cli

