--- 

# - name: create the json from the template
#   template:
#     src: rg_policy.j2
#     dest: /tmp/rg_policy.json

# - name: Create Azure Policy 
#   azure.azcollection.azure_rm_resource:
#     provider: "ResourceGroups"
#     resource_type: resourcegroup
#     resource_name: "{{ rg_policy }}"
#     api_version: "2020-01-01"
#     body: "{{ lookup ('file', 'rg-policy.json') }}"
#   register: output
#   failed_when: output.rc == 0 

- name: get the request token
  uri:
    method: PUT
    url: https://login.microsoftonline.com/64dc69e4-d083-49fc-9569-ebece1dd1408/oauth2/v2.0/token
    body:
      grant_type: client_credentials
      client_id: 44c04d85-b57a-46fb-ba2c-11044eb5ddb3
      client_secret: "{{ azure_secret }}"
      scope: https%3A%2F%2Fgraph.microsoft.com%2F.default
  register: token_out

- name:
  debug:
    msg: "{{ token_out }}"

- name: trying with URI
  uri:
    url: "{{ policy_creation_url }}"
    method: PUT
    headers:
      Authorization: Bearer "{{ azure_secret }}"
      Accept: application/json
    body_format: json
    body: "{{ lookup ('file', 'rg-policy.json') }}"


- name: debugging 
  debug:
    msg: "{{ output }}"

- name: Create Resource Group Policy
  azure.azcollection.azure_rm_devtestlabpolicy:
    resource_group: "{{ resource_group }}"
    lab_name: myLab
    policy_set_name: myPolicySet
    name: myPolicy
    fact_name: user_owned_lab_vm_count
    threshold: 5
