---

- name: create custom role for ARO workshop
  azure_rm_roledefinition:
    name: Custom Role for user-"{{ item }}"
    scope: /subscriptions/{{ sub.id }}/resourceGroups/user-{{ item }}
    permissions:
        - actions:
            - "Microsoft.Compute/virtualMachines/read"
          data_actions:
            - "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write"
    assignable_scopes:
        - "/subscriptions/{{ sub.id }}/resourceGroups/user-{{ item }}"
  with_sequence: start=1 end=10
  register: role_info
  tags: [ create, all ]

- name: getting roleid
  set_fact:
    ids: "{{ role_info |  json_query('results[].[id]') }}"
  tags: create

- name:
  debug:
    msg: "{{ ids  }}"
  tags: create

# - name: getting roleid
#   set_fact:
#     users: "{{ role_info |  json_query('results[].[item]') }}"
#   tags: create
# - name:
#   copy:
#     content: "{{ role_info.results }}"
#     dest: /tmp/role_out.json
#   tags: [ create ]

- name: assign custom roles to the User RG's
  azure_rm_roleassignment:
    scope: /subscriptions/{{ sub.id }}
    assignee_object_id: /subscriptions/{{ sub.id }}/resourceGroups/user-{{ item }}
    role_definition_id: "{{ ids[0][item] }}"  
  with_sequence: start=2 end=10
  tags: [ create, all ]


  