---



- name: delete policy assignment
  shell: |
    az policy assignment delete \
    --scope "{{ policy.assign.scope }}" \
    --policy "{{ policy.def.name }}" \
    --subscription "{{ subscription }}"
