---
# tasks file for azure-workshop
- name: Run Create tenant Playbook
  include_tasks: create_tenant.yaml
  tags: [ creat, all]

- name: Run Create Policy Playbook
  include_tasks: create_policy.yaml
  tags: [ create, all ]

- name: Run Create Resource Groups Playbook
  include_tasks: create_rg.yaml
  tags: [ create, all ]

- name: Run Create User
  include_tasks: create_users.yaml
  tags: [ create, all]
  
- name: Run Create User Roles Playbook
  include_tasks: create_user_roles.yaml
  tags: [ create, all ]

- name: Delete Resource Groups
  include_tasks: delete_rg.yaml
  tags: [ delete, all ]

- name: Delete Policy
  include_tasks: delete_policy.yaml
  tags: [ delete, all ]